[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@chainlink/contracts=lib/chainlink-brownie-contracts/contracts']
fs_permissions = [
    { access = "read", path = "./broadcast" },
] # thus us ti allow the vm.broadcast to access read operations

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
